
package airllinemanagement;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author elmnshawy
 */
public class ManagePassenger extends javax.swing.JFrame {

    /**
     * Creates new form ManagePassenger
     */
    public ManagePassenger() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        g = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ph = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 35, 35));
        jPanel1.setForeground(new java.awt.Color(35, 35, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(35, 35, 35));
        jTable1.setForeground(new java.awt.Color(35, 35, 35));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Passenger Name", "Gender", "Nationality", "passport Number", "Phone"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 121, 700, 430));

        pn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnActionPerformed(evt);
            }
        });
        jPanel1.add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Passenger Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, -1));
        jPanel1.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Gender");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 65, -1));

        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });
        jPanel1.add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Nationality");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 94, -1));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 120, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("passport Number");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        ph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phActionPerformed(evt);
            }
        });
        jPanel1.add(ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 120, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Phone");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 58, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Manage Passenger");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 220, -1));

        jButton5.setText("<--Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton2.setText("UPDATA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AirlLineManagement","root","PHW#84#jeor");
        String sql = "INSERT INTO managepassenger VALUES (?,?,?,?,?)";
        PreparedStatement ptst = con.prepareStatement(sql);
        ptst.setString(1, pn.getText());
        ptst.setString(2, g.getText()); // Flight Code
        ptst.setString(3, n.getText()); // Source
        ptst.setString(4, pass.getText()); // Destination
        ptst.setString(5, ph.getText()); // Takeoff
        // Validate and parse the value for noofseat
        String noOfSeatsText = pn.getText();
        if (!noOfSeatsText.isEmpty()) {
            int noOfSeats = Integer.parseInt(noOfSeatsText);
            ptst.setInt(5, noOfSeats); // No of Seats
        } else {
            // Handle the case where noofseat is empty
            // For example, you can set a default value or display an error message
            // Here, we'll set it to 0 as an example
            ptst.setInt(5, 0); // Default value
        }
        ptst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data inserted successfully");
        con.close();
    } catch (NumberFormatException e) {
        // Handle the case where the value for noofseat is not a valid integer
        JOptionPane.showMessageDialog(this, "Please enter a valid integer for No of Seats");
    } catch (Exception e) {
        // Handle other exceptions
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AirlLineManagement", "root", "PHW#84#jeor");

        String PassengerName = pn.getText();
        String Gender = g.getText();
        String Nationality = n.getText();
        String passportNumber = pn.getText();
        String Phone = ph.getText();
        String sql = "UPDATE managepassenger SET 'Passenger Name' = '"+pn+"', Gender = '"+g+"', Nationality = '"+n+"', passport Number = '"+pass+"',,Phone = '"+ph+"'";
      
       
        PreparedStatement ptst = con.prepareStatement(sql);
        ptst.setString(1, PassengerName);
        ptst.setString(2, Gender);
        ptst.setString(3, Nationality);
        ptst.setString(4, passportNumber);
        ptst.setString(5, Phone);
         int updatedRows = ptst.executeUpdate();
         
          if (updatedRows > 0) {
            JOptionPane.showMessageDialog(this, "Record updated successfully");
        } else {
             JOptionPane.showMessageDialog(this, "No record found with PassengerName: " + pn+"'");
        }
         con.close();
    } catch (SQLException e) {
        // Handle SQL exceptions
        JOptionPane.showMessageDialog(this, "SQL Error: " + e.getMessage());
        e.printStackTrace();
    } catch (Exception e) {
        // Handle other exceptions
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
        // Load the MySQL JDBC driver
        Class.forName("com.mysql.cj.jdbc.Driver");

        // Establish a connection to the database
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AirlLineManagement", "root", "PHW#84#jeor");

        // Prepare the SQL query to select all data from the 'manageflight' table
        String sql = "SELECT * FROM managepassenger";
        PreparedStatement ptst = con.prepareStatement(sql);

        // Execute the SQL query and get the result set
        ResultSet rs = ptst.executeQuery();

        // Get the table model from the jTable
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();

        // Clear existing rows in the table
        dt.setRowCount(0);

        // Iterate through the result set and add rows to the table model
        while (rs.next()) {
            Object[] rowData = {rs.getString("Passenger Name"), rs.getString("gender"), rs.getString("Nationality"), rs.getString("passport Number"), rs.getString("Phone")};
            dt.addRow(rowData);
        }

        // Close the connection and statement
        rs.close();
        ptst.close();
        con.close();
    } catch (ClassNotFoundException | SQLException e) {
        // Handle any exceptions
        JOptionPane.showMessageDialog(this, "Error: " + e);
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AirlLineManagement","root","PHW#84#jeor");
        
        // Create the SQL DELETE statement
        String name = n.getText();
        String sql = "DELETE FROM managepassenger WHERE name  = ?";
        
        // Create a PreparedStatement to prevent SQL injection
        PreparedStatement ptst = con.prepareStatement(sql);
        ptst.setString(1, name); // Set the value of the ID parameter
        
        // Execute the delete operation
        int deletedRows = ptst.executeUpdate();
        
        if (deletedRows > 0) {
            JOptionPane.showMessageDialog(this, "Record deleted successfully");
        } else {
            JOptionPane.showMessageDialog(this, "No record found with name: " + name+"'");
        }
        
        con.close();
    } catch (ClassNotFoundException | SQLException e) {
        // Handle any exceptions
       JOptionPane.showMessageDialog(this, "Error: " + e);
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void phActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phActionPerformed
        // TODO add your handling code here:
       String inputString = ph.getText(); 

    try {
        
        int phoneNumber = Integer.parseInt(inputString);

    } catch (NumberFormatException ex) {

        System.out.println("Please enter a valid integer for the phone number.");
    }


    }//GEN-LAST:event_phActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         dashboard obj = new dashboard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePassenger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField g;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField n;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField ph;
    private javax.swing.JTextField pn;
    // End of variables declaration//GEN-END:variables
}
