package airllinemanagement;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;


public class ManageFlight extends javax.swing.JFrame {

    /**
     * Creates new form ManageFlight
     */
    public ManageFlight() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Fc = new javax.swing.JTextField();
        D = new javax.swing.JTextField();
        S = new javax.swing.JTextField();
        TF = new javax.swing.JTextField();
        NOS = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jButton4.setText("jButton1");

        jButton6.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 35, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Flight Code");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setText("Source");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel4.setText("Destination");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel6.setText("Take of");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 40, -1));

        jLabel7.setText("No of Seats");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jTable1.setBackground(new java.awt.Color(35, 35, 35));
        jTable1.setForeground(new java.awt.Color(35, 35, 35));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flighe Code", "Source", "Destination", "Take of", "No of Seats"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 520, 410));

        Fc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FcActionPerformed(evt);
            }
        });
        jPanel1.add(Fc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel1.add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));
        jPanel1.add(S, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));
        jPanel1.add(TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));
        jPanel1.add(NOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, -1, -1));

        jButton2.setText("UPDATA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, -1, -1));

        jButton5.setText("DELETE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, -1, -1));

        jButton7.setText("SEARCH");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Manager Flight");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 190, 30));

        jButton3.setText("<--Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         try {
        // Load the MySQL JDBC driver
        Class.forName("com.mysql.cj.jdbc.Driver");

        // Establish a connection to the database
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AirlLineManagement", "root", "PHW#84#jeor");

        // Prepare the SQL query to select all data from the 'manageflight' table
        String sql = "SELECT * FROM managepassenger";
        PreparedStatement ptst = con.prepareStatement(sql);

        // Execute the SQL query and get the result set
        ResultSet rs = ptst.executeQuery();

        // Get the table model from the jTable
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();

        // Clear existing rows in the table
        dt.setRowCount(0);

        // Iterate through the result set and add rows to the table model
        while (rs.next()) {
            Object[] rowData = {rs.getString("Passenger Name"), rs.getString("gender"), rs.getString("Nationality"), rs.getString("passport Number"), rs.getString("Phone")};
            dt.addRow(rowData);
        }

        // Close the connection and statement
        rs.close();
        ptst.close();
        con.close();
    } catch (ClassNotFoundException | SQLException e) {
        // Handle any exceptions
        JOptionPane.showMessageDialog(this, "Error: " + e);
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AirlLineManagement","root","PHW#84#jeor");
        String sql = "INSERT INTO managepassenger VALUES (?,?,?,?,?)";
        PreparedStatement ptst = con.prepareStatement(sql);
         ptst.setString(1, fc.getText());
        ptst.setString(2, s.getText()); // Flight Code
        ptst.setString(3, d.getText()); // Source
        ptst.setString(4, TF.getText()); // Destination
        ptst.setString(5, NOS.getText()); // Takeoff
        // Validate and parse the value for noofseat
        String NoofSeatsText = NOS.getText();
        if (!NoofSeatsText.isEmpty()) {
            int noOfSeats = Integer.parseInt(NoofSeatsText);
            ptst.setInt(5, noOfSeats); // No of Seats
        } else {
            // Handle the case where noofseat is empty
            // For example, you can set a default value or display an error message
            // Here, we'll set it to 0 as an example
            ptst.setInt(5, 0); // Default value
        }
        ptst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data inserted successfully");
        con.close();
    } catch (NumberFormatException e) {
        // Handle the case where the value for noofseat is not a valid integer
        JOptionPane.showMessageDialog(this, "Please enter a valid integer for No of Seats");
    } catch (Exception e) {
        // Handle other exceptions
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AirlLineManagement", "root", "PHW#84#jeor");

        String FlightCode = fc.getText();
        String Source = s.getText();
        String Destination = d.getText();
        String Takeof = TF.getText();
        String NoofSeats = NOS.getText();
        String sql = "UPDATE managepassenger SET 'Passenger Name' = '"+fc+"', Flight Code = '"+s+"', Source = '"+d+"', Destination = '"+TF+"',,Take of = '"+NOS+"No of Seats";
      
       
        PreparedStatement ptst = con.prepareStatement(sql);
        ptst.setString(1, FlightCode);
        ptst.setString(2, Source);
        ptst.setString(3, Destination);
        ptst.setString(4, Takeof);
        ptst.setString(5, NoofSeats);
         int updatedRows = ptst.executeUpdate();
         
          if (updatedRows > 0) {
            JOptionPane.showMessageDialog(this, "Record updated successfully");
        } else {
             JOptionPane.showMessageDialog(this, "No record found with PassengerName: " + NOS+"'");
        }
         con.close();
    } catch (SQLException e) {
        // Handle SQL exceptions
        JOptionPane.showMessageDialog(this, "SQL Error: " + e.getMessage());
        e.printStackTrace();
    } catch (Exception e) {
        // Handle other exceptions
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
          try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AirlLineManagement","root","PHW#84#jeor");
        
        // Create the SQL DELETE statement
        String FlightCode = fc.getText();
        String sql = "DELETE FROM managepassenger WHERE name  = ?";
        
        // Create a PreparedStatement to prevent SQL injection
        PreparedStatement ptst = con.prepareStatement(sql);
        ptst.setString(1, FlightCode); // Set the value of the ID parameter
        
        // Execute the delete operation
        int deletedRows = ptst.executeUpdate();
        
        if (deletedRows > 0) {
            JOptionPane.showMessageDialog(this, "Record deleted successfully");
        } else {
            JOptionPane.showMessageDialog(this, "No record found with name: " + FlightCode+"'");
        }
        
        con.close();
    } catch (ClassNotFoundException | SQLException e) {
        // Handle any exceptions
       JOptionPane.showMessageDialog(this, "Error: " + e);
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void FcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FcActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         dashboard obj = new dashboard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageFlight().setVisible(true);
            }
        });
    }
private javax.swing.JTextField fc;
private javax.swing.JTextField s;
private javax.swing.JTextField d;
private javax.swing.JTextField tof;
private javax.swing.JTextField nos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField D;
    private javax.swing.JTextField Fc;
    private javax.swing.JTextField NOS;
    private javax.swing.JTextField S;
    private javax.swing.JTextField TF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
