package airllinemanagement;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TicketBooking extends javax.swing.JFrame {

    /**
     * Creates new form TicketBooking
     */
    public TicketBooking() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ge = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        na = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        pn = new javax.swing.JTextField();
        fc = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        g = new javax.swing.JTextField();
        am = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 35, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Passenger Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Passenger Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 100, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Flight Code");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        ge.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ge.setText("Gender");
        jPanel1.add(ge, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Passenger Number ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        a.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        a.setText("Amount");
        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, -1, -1));

        na.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        na.setText("Nationality");
        jPanel1.add(na, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 100, -1));
        jPanel1.add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 110, -1));
        jPanel1.add(fc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 100, -1));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, -1));
        jPanel1.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 110, -1));
        jPanel1.add(am, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 120, -1));
        jPanel1.add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 100, -1));

        jTable1.setBackground(new java.awt.Color(35, 35, 35));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Passenger Id", "Passenger Name", "Flight Code", "Gender", "Passenger Number ", "Amount", "Nationality"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 900, 410));

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton2.setText("Save");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 560, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, -1, -1));

        jButton4.setText("<--Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pass.setText("");
        ID.setText("");
        pn.setText("");
        fc.setText("");
        na.setText("");
        ge.setText("");
        a.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          try {
        // Load the MySQL JDBC driver
        Class.forName("com.mysql.cj.jdbc.Driver");

        // Establish a connection to the database
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AirlLineManagement", "root", "PHW#84#jeor");

        // Prepare the SQL query to select all data from the 'manageflight' table
        String sql = "SELECT * FROM TicketBooking";
        PreparedStatement ptst = con.prepareStatement(sql);

        // Execute the SQL query and get the result set
        ResultSet rs = ptst.executeQuery();

        // Get the table model from the jTable
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();

        // Clear existing rows in the table
        dt.setRowCount(0);

        // Iterate through the result set and add rows to the table model
        while (rs.next()) {
            Object[] rowData = {rs.getString("Passenger Number "), rs.getString("Passenger Id"), rs.getString("Flight Code"), rs.getString("Nationality"), rs.getString("Gender")};
            dt.addRow(rowData);
        }

        // Close the connection and statement
        rs.close();
        ptst.close();
        con.close();
    } catch (ClassNotFoundException | SQLException e) {
        // Handle any exceptions
        JOptionPane.showMessageDialog(this, "Error: " + e);
        e.printStackTrace();
    } catch (Exception e) { 
            Logger.getLogger(TicketBooking.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         dashboard obj = new dashboard();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //FlatMacLightLaf.setup();
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JLabel a;
    private javax.swing.JTextField am;
    private javax.swing.JTextField fc;
    private javax.swing.JTextField g;
    private javax.swing.JLabel ge;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField n;
    private javax.swing.JLabel na;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField pn;
    // End of variables declaration//GEN-END:variables
}
